[top_menu]
date = ["2016年7月","2016年8月","2016年9月","2016年10月","2016年11月","2016年12月","2017年1月","2017年2月","2017年3月","2017年4月","2017年5月","2017年6月","2017年7月"]

place = ["松戸駅周辺","矢切地区","五香常盤平地区","小金原地区","新松戸地区","東松戸地区"]

organizer = ["政府", "千葉県", "松戸市", "教育委員会", "商工会議所", "NPO団体", "任意団体"]

target = ["事業者", "乳幼児", "未就学児", "小学生", "中学生", "高校生", "大学生", "若者", "求職者", "両親", "高齢者", "障害者", "貧困者"]

[side_menu]

[footer]

item = ["利用規約", "プライバシーポリシー", "運営会社", "お問い合わせ窓口"]
